### ISSUE TITLE
Management API Socket Server Crashes When Invalid Command Received

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#47]
When an invalid response is received, the following error happens:

```Exception in thread Thread-1:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/BrainGenix/System/Core/Management/API/ManagementAPI.py", line 65, in ManagementAPIThread
    self.Command = json.loads(self.Command)
  File "/usr/lib/python3.8/json/__init__.py", line 357, in loads
    return _default_decoder.decode(s)
  File "/usr/lib/python3.8/json/decoder.py", line 337, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/usr/lib/python3.8/json/decoder.py", line 355, in raw_decode
    raise JSONDecodeError("Expecting value", s, err.value) from None
```

**Comment by datacrystals** [comment]
Turned out to be a TypeError, just had to convert exception object to a string then the JSON lib was able to serialize it.
