### ISSUE TITLE
PyMySQL Packet Sequence Issue

### ISSUE THREAD

**Issue by datacrystals** [carboncopies/BrainGenix-NES#57]
Pymysql seems to be crashing for no apparent reason. Not sure what's going on here:

```Exception in thread Zookeeper Leader Timeout Checker:
Traceback (most recent call last):
  File "/usr/lib/python3.8/threading.py", line 932, in _bootstrap_inner
    self.run()
  File "/usr/lib/python3.8/threading.py", line 870, in run
    self._target(*self._args, **self._kwargs)
  File "/home/BrainGenix/System/Core/Internode/Zookeeper/Zookeeper.py", line 268, in LeaderCheckDaemon
    self.LeaderTimeout()
  File "/home/BrainGenix/System/Core/Internode/Zookeeper/Zookeeper.py", line 352, in LeaderTimeout
    self.AutoInitZKLeader()
  File "/home/BrainGenix/System/Core/Internode/Zookeeper/Zookeeper.py", line 149, in AutoInitZKLeader
    self.ElectLeader()
  File "/home/BrainGenix/System/Core/Internode/Zookeeper/Zookeeper.py", line 177, in ElectLeader
    self.Logger.Log('Election Complete')
  File "/home/BrainGenix/System/Core/Management/Logger/Logger.py", line 188, in Log
    self.LoggerCursor.execute(insertStatement,val)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 705, in _read_packet
    raise err.InternalError(
pymysql.err.InternalError: Packet sequence number wrong - got 187 expected 2
Traceback (most recent call last):
  File "Main.py", line 130, in <module>
    LFTMInstance.MainLoop()
  File "/home/BrainGenix/System/Core/Internode/Zookeeper/LFTransitionManager.py", line 92, in MainLoop
    self.SystemTelemetryManager.TransitionLeader()
  File "/home/BrainGenix/System/Core/LFTM/SystemTelemetryManager.py", line 34, in TransitionLeader
    self.SysTelFollower = Follower(Logger=self.Logger, Zookeeper=self.Zookeeper)
  File "/home/BrainGenix/System/Core/Management/Telemetry/SystemTelemetry.py", line 36, in __init__
    self.Logger.Log('Collecting System Information')
  File "/home/BrainGenix/System/Core/Management/Logger/Logger.py", line 188, in Log
    self.LoggerCursor.execute(insertStatement,val)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 148, in execute
    result = self._query(query)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/cursors.py", line 310, in _query
    conn.query(q)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 548, in query
    self._affected_rows = self._read_query_result(unbuffered=unbuffered)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 775, in _read_query_result
    result.read()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 1156, in read
    first_packet = self.connection._read_packet()
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 711, in _read_packet
    recv_data = self._read_bytes(bytes_to_read)
  File "/home/tliao/.local/lib/python3.8/site-packages/pymysql/connections.py", line 729, in _read_bytes
    self._sock.settimeout(self._read_timeout)
OSError: [Errno 9] Bad file descriptor
```

Seems to happen when starting and stopping the system frequently, perhaps something mysql is doing is misbehaving?

**Comment by PRISHIta123** [comment]
This issue occurs when multithreading is used, one core returning values after processing one thread before another core returns them for another thread. You would need a separate pymysql connection for each thread.

**Comment by PRISHIta123** [comment]
Is a management API thread created for each socket, that is one for each node? There will be 11 threads in that case.

**Comment by datacrystals** [comment]
@PRISHIta123 

Thanks for looking into this! Currently we're basically ignoring the other threads, so perhaps we should make some other interface system for the db interface. We did trace the problem back to the management API, and Arseniy is looking into fixing that. We'll just need to make a note for the database interface to exclusively work with that by creating new threads.

**Comment by datacrystals** [comment]
@amukovozov How is your progress going so far with the Logger?

**Comment by datacrystals** [comment]
Resolved finally.
